let session, intent, events=[];
const $=id=>document.getElementById(id);
const text=(tag,value)=>{const el=document.createElement(tag);el.textContent=value;return el;};
const status=(message,error=false)=>{$('status').textContent=message;$('status').className=error?'error':'';};
async function request(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,csrf:session?.csrf})}:{});const result=await r.json();if(!r.ok)throw Error(result.error||'Richiesta non completata.');return result;}
async function tool(name,args={}){return request('/api/tool',{name,arguments:args});}
async function audit(){events=(await request('/api/audit')).events;$('events').replaceChildren(...events.slice().reverse().map(e=>{const row=text('div',({login_authorized:'Accesso autorizzato',availability_viewed:'Disponibilità consultate',booking_prepared:'Appuntamento preparato',booking_confirmed:'Conferma della persona',booking_created:'Ricevuta creata',booking_cancelled:'Appuntamento annullato',session_revoked:'Sessione revocata'})[e.action]||e.action);row.className='event';row.prepend(text('time',new Date(e.at).toLocaleTimeString('it-IT')));return row;}));}
async function refresh(){const result=await tool('demo_availability');$('slots').replaceChildren(...result.slots.map(s=>{const b=document.createElement('button');b.className='slot';b.append(text('strong',s.label.split(' · ')[1]),text('span',s.available?'Prepara appuntamento':'Già occupato'));b.disabled=!s.available;b.onclick=()=>run(async()=>{const r=await tool('demo_prepare_booking',{slot:s.id});intent=r.intent;$('summary').textContent=s.label+' · '+session.user;$('confirmation').hidden=false;status('Appuntamento preparato. Controlla e conferma.');await audit();});return b;}));$('bookings').replaceChildren(...result.bookings.map(b=>{const row=text('div',b.label+' · '+(b.status==='cancelled'?'Annullato':'Prenotato'));row.className='receipt';row.append(text('p',b.id));if(b.status==='booked'){const btn=text('button','Annulla appuntamento');btn.className='secondary';btn.onclick=()=>run(async()=>{if(!window.confirm('Annullare '+b.label+'?'))return;await request('/api/cancel',{id:b.id});status('Appuntamento annullato. L’orario è nuovamente disponibile.');await refresh();});row.append(btn);}return row;}));if(!result.bookings.length)$('bookings').append(text('p','Non hai ancora prenotazioni.'));await audit();}
let busy=false;
async function run(fn){if(busy)return;busy=true;try{await fn();}catch(e){status(e.message,true);}finally{busy=false;}}
$('login').onclick=()=>run(async()=>{if(session.authenticated)await request('/oauth/revoke',{});location.href='/login';});
$('confirm').onclick=()=>run(async()=>{const r=await request('/api/confirm',{intent});intent=null;$('confirmation').hidden=true;status('Prenotazione creata. Ricevuta '+r.booking.id);await refresh();});
$('discard').onclick=()=>{intent=null;$('confirmation').hidden=true;status('Preparazione abbandonata. Nessuna prenotazione creata.');};
$('audit').onclick=()=>run(audit);
$('export').onclick=()=>run(async()=>{await audit();const url=URL.createObjectURL(new Blob([JSON.stringify({demo:true,events},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='portale-italia-attivita-demo.json';a.click();URL.revokeObjectURL(url);});
$('ipa').onsubmit=e=>{e.preventDefault();run(async()=>{$('iparesult').textContent='Ricerca in corso…';try{$('iparesult').textContent=JSON.stringify(await tool('ipa_search_entities',{query:$('query').value,limit:5,offset:0}),null,2);}catch(e){$('iparesult').textContent=e.message;throw e;}});};
run(async()=>{session=await request('/api/session');if(session.authenticated){$('identity').textContent=session.user;$('login').textContent='Cambia utente';await refresh();const pendingId=new URLSearchParams(location.search).get('intent');if(pendingId){const p=await request('/api/pending?intent='+encodeURIComponent(pendingId));intent=p.intent;$('summary').textContent=p.slot.label+' · '+session.user;$('confirmation').hidden=false;status('Richiesta preparata dall’agente: controlla e conferma.');}}else{$('slots').append(text('p','Collega un utente dimostrativo per provare.'));status('Puoi usare Alice o Bob. Nessun dato personale richiesto.');}});
